import { StyleSheet } from "react-native";

export const chatPageStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#03ad75",
    paddingLeft: 17,
    paddingRight: 20,
    paddingTop: 35,
    paddingBottom: 20,
    width: "100%",
    elevation: 5,
  },
  avatar: {
    height: 65,
    width: 65,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgb(237, 239, 242)",
    marginLeft: 15,
  },
  msg_footer: {
    paddingVertical: 20,
    paddingHorizontal: 10,
    backgroundColor: "white",
    elevation: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  msgInput: {
    height: 70,
    paddingHorizontal: 20,
    backgroundColor: "rgb(237, 239, 242)",
    flex: 1,
    fontSize: 17,
    borderRadius: 15,
    elevation: 3,
  },
  msg_main_container: {
    width: "100%",
    marginVertical: 5,
    paddingBottom: 30,
  },
  msgBox: {
    padding: 10,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    position: "relative",
    flex:1,
    elevation: 5,
    minHeight: 70,
    maxHeight: "auto",
    marginTop: 33,
    justifyContent: "center",
    alignItems: "center",
  },
  msgTxt: {
    minWidthL:"100%",
    maxWidth: "100%",
    fontSize: 16,
    marginHorizontal: 10,
    flexWrap: "wrap",
    lineHeight: 22,
  },
  msg_arrow: {
    position: "absolute",
    top: -7,
  },
  msg_avatar: {
    height: 60,
    width: 60,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
    margin: 15,
    elevation: 5,
  },
  userFullName: {
    color: "white",
    fontSize: 22,
    marginLeft: 10,
  },
});
